### ISSUE TITLE
Only plain text being displayed

### ISSUE THREAD

**Issue by iampaulmata** [IqbalMind/Stream-Overlay-Html-Css#1]
Followed the "how to use" instructions in the readme file but found that I was only seeing plain text displayed. Opened the html files in a text editor and found that the wrong stylesheet was being called. The stylesheet being called is "test.css" but the actual stylesheet name is "style.css".

Updated both html files to call the correct stylesheet and I see the overlays displayed correctly.

**Comment by iampaulmata** [comment]
Two pull requests waiting for merge to fix the stylesheet name issue

**Comment by IqbalMind** [comment]
Thank a lot for reminding me
